name: frontend

on:
  push:
    branches: [main, dev]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: "256603361470.dkr.ecr.ap-south-1.amazonaws.com"
  ECR_REPO: cloudkitchen-app-repo

jobs:
  build:
    name: build · frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present || true

      - name: Test
        run: CI=true npm test --if-present || true

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: frontend
          severity: HIGH,CRITICAL
          exit-code: '0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR login
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build image
        working-directory: '.'
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPO:${{ github.sha }} \
            frontend

          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPO:${{ github.sha }} $ECR_REGISTRY/$ECR_REPO:latest
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPO:${{ github.sha }} $ECR_REGISTRY/$ECR_REPO:dev-latest
          fi

      - name: Push image to ECR
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: |
          docker push $ECR_REGISTRY/$ECR_REPO:${{ github.sha }}

          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker push $ECR_REGISTRY/$ECR_REPO:latest
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            docker push $ECR_REGISTRY/$ECR_REPO:dev-latest
          fi
